import { Permissions } from "../types";

const {
  Roles: {
    SUPER_ADMIN,
    ORGANIZATION_ADMIN,
    ORGANIZATION_MANAGER,
    PROJECT_MANAGER,
    PROJECT_MEMBER,
  },
  Resources: {
    ORGANIZATION,
    ORGANIZATION_INVITATIONS,
    ORGANIZATION_MEMBERS,
    ORGANIZATION_SEATS,
    ORGANIZATION_ACCESS_LOGS,
    ORGANIZATION_PROJECTS,
    ORGANIZATION_PROJECT_DOCS,
    ORGANIZATION_PROJECT_INVITATIONS,
    ORGANIZATION_PROJECT_MEMBERS,
    ORGANIZATION_KNOWLEDGE_BASES,
    ORGANIZATION_KNOWLEDGE_BASES_DOCS,
    PROJECT_ISSUES,
  },
} = Permissions;

export default class Constants {
  static RoleHierarchy: Permissions.Roles[] = [
    SUPER_ADMIN,
    ORGANIZATION_ADMIN,
    ORGANIZATION_MANAGER,
    PROJECT_MANAGER,
    PROJECT_MEMBER,
  ];

  static OrganizationResources: Permissions.Resources[] = [
    ORGANIZATION,
    ORGANIZATION_INVITATIONS,
    ORGANIZATION_MEMBERS,
    ORGANIZATION_SEATS,
    ORGANIZATION_ACCESS_LOGS,
    ORGANIZATION_PROJECTS,
  ];

  static OrganizationProjectResources: Permissions.Resources[] = [
    ORGANIZATION_PROJECT_DOCS,
    ORGANIZATION_PROJECT_INVITATIONS,
    ORGANIZATION_PROJECT_MEMBERS,
    PROJECT_ISSUES,
  ];

  static OrganizationKnowledgeBaseResources: Permissions.Resources[] = [
    ORGANIZATION_KNOWLEDGE_BASES,
    ORGANIZATION_KNOWLEDGE_BASES_DOCS,
  ];
}
