import { Router } from "express";
import { Permissions } from "../permissions/permissions.types";
import * as handlers from "./knowledge-bases.handlers";
import PermissionsMiddlewares from "../permissions/permissions.middlewares";
import accessLogsRouter from "./access-logs/access-logs.routes";
export default Router()
  .post(
    "/",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES,
      Permissions.Actions.CREATE
    ),
    handlers.createKnowledgeBase
  )
  .get(
    "/",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES,
      Permissions.Actions.READ
    ),
    handlers.listKnowledgeBases
  )
  .get(
    "/:knowledgeBaseId",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES,
      Permissions.Actions.READ
    ),
    handlers.getKnowledgeBase
  )
  .patch(
    "/:knowledgeBaseId",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES,
      Permissions.Actions.UPDATE
    ),
    handlers.updateKnowledgeBase
  )
  .delete(
    "/:knowledgeBaseId",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES,
      Permissions.Actions.DELETE
    ),
    handlers.deleteKnowledgeBase
  )
  .post(
    "/:knowledgeBaseId/documents",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES_DOCS,
      Permissions.Actions.CREATE
    ),
    handlers.uploadDocs
  )
  .get(
    "/:knowledgeBaseId/document",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES_DOCS,
      Permissions.Actions.READ
    ),
    handlers.getDocument
  )
  .get(
    "/:knowledgeBaseId/documents",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES_DOCS,
      Permissions.Actions.READ
    ),
    handlers.getDocs
  )
  .delete(
    "/:knowledgeBaseId/documents",
    PermissionsMiddlewares.knowledgeBases(
      Permissions.Resources.ORGANIZATION_KNOWLEDGE_BASES_DOCS,
      Permissions.Actions.DELETE
    ),
    handlers.deleteDocs
  )
  .use(
    "/:knowledgeBaseId/access-logs",
    accessLogsRouter
  );
