services:
  pg:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mini_io:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  gitea:
    image: docker.io/gitea/gitea:1.23.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # Database configuration
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=pg:5432
      - GITEA__database__NAME=postgres
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=postgres
      # LFS Storage configuration
      - GITEA__storage__STORAGE_TYPE=minio
      - GITEA__storage__PROVIDER=minio
      - GITEA__storage__PATH=/data/gitea/attachments
      - GITEA__storage__MINIO_ENDPOINT=minio:9000
      - GITEA__storage__MINIO_ACCESS_KEY_ID=minioadmin
      - GITEA__storage__MINIO_SECRET_ACCESS_KEY=minioadmin123
      - GITEA__storage__MINIO_BUCKET=gitea-lfs
      - GITEA__storage__MINIO_LOCATION=us-east-1
      - GITEA__storage__MINIO_USE_SSL=false
      - GITEA__storage__MINIO_INSECURE_SKIP_VERIFY=true
      - GITEA__storage__SERVE_DIRECT=false
      - GITEA__storage__MINIO_BUCKET_LOOKUP_TYPE=path
      # Server configuration
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__REQUIRE_SIGNIN_VIEW=true
    networks:
      - app-network
    volumes:
      - gitea_data:/data
      - ./app.ini:/data/gitea/conf/app.ini
      - etc_timezone:/etc/timezone:ro
      - etc_localtime:/etc/localtime:ro
    ports:
      - "4002:3000"
      - "222:22"
    depends_on:
      - pg
      - mini_io

volumes:
  pg_data:
    driver: local
  minio_data:
    driver: local
  gitea_data:
    driver: local
  etc_timezone:
    driver: local
  etc_localtime:
    driver: local

networks:
  app-network:
    driver: bridge
