import { MarkdownViewer } from "@/features/chat/messages/components";

export function PrivacyPolicyPage() {
  return (
    <div className="h-screen w-screen overflow-y-auto flex justify-center">
      <div className="max-w-5xl py-12 h-full w-full ">
        <MarkdownViewer
          content={`## Privacy Policy - Syykick (Syyclops)

This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Syykick platform and tells you about your privacy rights and how the law protects you. We use your personal data to provide and improve our building engineering AI assistant services. By using the platform, you agree to the collection and use of information in accordance with this Privacy Policy.

## Interpretation and Definitions

### Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

### Definitions

For the purposes of this Privacy Policy:

- **Account** means a unique account created for you to access our platform or parts of our platform.
- **Affiliate** means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
- **Company** (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Syyclops Inc., 1415 Elliot Pl NW, Washington, DC 20007.
- **Cookies** are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.
- **Country** refers to: United States
- **Device** means any device that can access the platform such as a computer, a cellphone or a digital tablet.
- **Personal Data** is any information that relates to an identified or identifiable individual.
- **Service** refers to the Syykick platform.
- **Service Provider** means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
- **Building Engineering Data** refers to any building-related information, blueprints, specifications, or technical data that you upload or create while using our platform.
- **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
- **Website** refers to Syykick, accessible from syykick.com
- **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

## Collecting and Using Your Personal Data

### Types of Data Collected

#### Personal Data

While using our platform, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:

- Email address
- First and last name
- Phone number
- Company name and job title
- Professional credentials and certifications
- Usage Data

#### Building Engineering Data

As our platform is specifically designed for building engineering projects, you may upload or create:

- Building plans and blueprints
- Technical specifications
- Project documentation
- Engineering calculations
- Building system information
- Other technical data related to your projects

We treat this information with the highest level of confidentiality and security, as detailed in the "Security of Your Data" section below.

#### Usage Data

Usage Data is collected automatically when using the platform.

Usage Data may include information such as your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our platform that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When you access the platform by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.

We may also collect information that your browser sends whenever you visit our platform or when you access the platform by or through a mobile device.

#### AI Interaction Data

When you interact with our AI assistant, we collect:

- Queries and prompts you submit
- AI-generated responses
- Feedback you provide on AI responses
- Usage patterns and frequency of interactions

This data helps us improve the accuracy and relevance of our AI assistant for building engineering applications.

### Tracking Technologies and Cookies

We use Cookies and similar tracking technologies to track the activity on our platform and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our platform. The technologies we use may include:

- **Cookies or Browser Cookies.** A cookie is a small file placed on your Device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our platform. Unless you have adjusted your browser setting so that it will refuse Cookies, our platform may use Cookies.
- **Web Beacons.** Certain sections of our platform and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).

Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser.

We use both Session and Persistent Cookies for the purposes set out below:

- **Necessary / Essential Cookies**
  - Type: Session Cookies
  - Administered by: Us
  - Purpose: These Cookies are essential to provide you with services available through the platform and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and we only use these Cookies to provide you with those services.

- **Cookies Policy / Notice Acceptance Cookies**
  - Type: Persistent Cookies
  - Administered by: Us
  - Purpose: These Cookies identify if users have accepted the use of cookies on the platform.

- **Functionality Cookies**
  - Type: Persistent Cookies
  - Administered by: Us
  - Purpose: These Cookies allow us to remember choices you make when you use the platform, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the platform.

- **Analytics and Performance Cookies**
  - Type: Persistent Cookies
  - Administered by: Third-Party Analytics Providers
  - Purpose: These cookies help us understand how visitors interact with our platform by collecting and reporting information anonymously. They help us improve the way our platform works.

## Use of Your Personal Data

The Company may use Personal Data for the following purposes:

- **To provide and maintain our platform**, including to monitor the usage of our platform.
- **To manage your Account**: to manage your registration as a user of the platform. The Personal Data you provide can give you access to different functionalities of the platform that are available to you as a registered user.
- **For the performance of a contract**: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the platform.
- **To improve our AI assistant**: We use your interactions with our AI to train and improve its responses for building engineering applications.
- **To contact you**: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
- **To provide you with news, special offers and general information** about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.
- **To manage your requests**: To attend and manage your requests to us.
- **For business transfers**: We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by us about our platform users is among the assets transferred.
- **For other purposes**: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our platform, products, services, marketing and your experience.

### Building Engineering Data Usage

We use your Building Engineering Data specifically to:

- Provide you with AI-assisted analysis and recommendations
- Help you manage and organize your building projects
- Enable collaboration with your team members and partners
- Improve our understanding of building engineering needs and challenges
- Enhance our AI's ability to provide relevant building engineering assistance

We do not use your Building Engineering Data to market to you or share it with third parties for advertising purposes.

## Sharing Your Personal Information

We may share your personal information in the following situations:

- **With Service Providers**: We may share your personal information with Service Providers to monitor and analyze the use of our platform, to contact you.
- **For business transfers**: We may share or transfer your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.
- **With Affiliates**: We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.
- **With business partners**: We may share your information with our business partners to offer you certain products, services or promotions.
- **With your consent**: We may disclose your personal information for any other purpose with your consent.
- **With your team members**: If you are part of an organization account, we may share your Building Engineering Data with other members of your organization as necessary to facilitate collaboration.

## Retention of Your Personal Data

The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our platform, or we are legally obligated to retain this data for longer time periods.

For Building Engineering Data, we will retain this information for the duration of your account plus an additional period of up to 90 days after account termination to allow you to retrieve your data if needed.

## Transfer of Your Personal Data

Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.

## Delete Your Personal Data

You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you.

Our platform may give you the ability to delete certain information about you from within the platform. You may also contact us to request access to, correct, or delete any personal information that you have provided to us.

For Building Engineering Data, you can export your data at any time before deleting your account. Once you request account deletion, we will initiate the process to permanently remove your data after the retention period described above.

Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.

## Disclosure of Your Personal Data

### Business Transactions

If the Company is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.

### Law enforcement

Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).

### Other legal requirements

The Company may disclose your Personal Data in the good faith belief that such action is necessary to:

- Comply with a legal obligation
- Protect and defend the rights or property of the Company
- Prevent or investigate possible wrongdoing in connection with the platform
- Protect the personal safety of users of the platform or the public
- Protect against legal liability

## Security of Your Personal Data

The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.

For Building Engineering Data, we implement additional security measures:

- End-to-end encryption for sensitive building data
- Regular security audits and penetration testing
- Strict access controls and authentication requirements
- Secure backup systems
- Employee training on data security protocols

## Children's Privacy

Our platform does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.

If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.

## Links to Other Websites

Our platform may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

## Changes to this Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via email and/or a prominent notice on our platform, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`}
        />
        <div className="h-32"></div>
      </div>
    </div>
  );
}
