export const CONFIG = {
  PORT: process.env.PORT || 4000,
  CORS_ORIGINS: [
    process.env.FRONTEND_URL!,
    "https://syykick.com",
    "https://www.syykick.com",
    "https://yo.syyclops.com",
    "https://www.yo.syyclops.com",
    "https://yo-syyclops.vercel.app",
    "https://timely-faun-d79ed5.netlify.app/",
    "https://syy-mastra.netlify.app",
  ],
  COOKIE_OPTIONS: {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax" as const,
    domain: process.env.NODE_ENV === "production" ? ".syykick.com" : "",
    path: "/",
  },
  EMAIL_WHITELIST: [
    "mgkurass@gmail.com",
    "gopal24krishna@gmail.com",
    "ben.montalbano12@gmail.com",
    "adi.mechie@gmail.com",
    "quentinnippert@gmail.com",
  ],
  __prod__: process.env.NODE_ENV === "production",
};

export const MARKITDOWN_MIME_TYPES = [
  //   "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/msword",
  "text/markdown",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.ms-powerpoint",
  "text/html",
  "text/csv",
  "text/xml",
  "application/zip",
];

export const PROGRAMMING_FILE_MIME_TYPES = [
  "application/json",
  // JavaScript ecosystem
  "application/javascript",
  "application/x-javascript",
  "text/javascript",
  "text/x-javascript",
  "application/typescript",
  "text/typescript",
  "text/x-typescript",
  "text/jsx",
  "text/x-jsx",
  "text/tsx",
  "text/x-tsx",
  "text/x-vue",
  "application/node",

  // Python
  "application/x-python",
  "text/python",
  "text/x-python",
  "text/x-python-script",
  "text/x-script.python",
  "application/x-python-code",

  // Other programming languages
  "text/x-java-source",
  "text/x-java",
  "text/x-kotlin",
  "text/x-scala",
  "text/x-c",
  "text/x-c++",
  "text/x-cpp",
  "text/x-chdr",
  "text/x-csrc",
  "text/x-csharp",
  "text/x-fsharp",
  "text/x-go",
  "text/x-rust",
  "text/x-swift",
  "text/x-php",
  "application/x-httpd-php",
  "text/x-ruby",
  "text/x-scss",
  "text/x-sass",
  "text/x-less",
  "text/x-haskell",
  "text/x-ocaml",
  "text/x-erlang",
  "text/x-elixir",
  "text/x-clojure",
  "text/x-lisp",
  "text/x-scheme",
  "text/x-r",
  "text/x-matlab",
  "text/x-octave",
  "text/x-julia",
  "text/x-perl",
  "text/x-lua",
  "text/x-tcl",
  "text/x-awk",
  "text/x-shellscript",
  "application/x-sh",
  "text/x-bash",
  "text/x-zsh",
  "text/x-fish",
  "text/x-powershell",
  "text/x-batch",
  "application/x-bat",
  "text/x-dockerfile",
  "text/x-makefile",
  "text/x-sql",
  "application/sql",
  "text/x-mysql",
  "text/x-postgresql",
  "text/x-vhdl",
  "text/x-verilog",
  "text/x-systemverilog",
  "text/x-asm",
  "text/x-nasm",
];
