name: Deploy Mastra to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mastra-app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        working-directory: .

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          NETLIFY_SCOPE: ${{ secrets.NETLIFY_SCOPE }}
          NETLIFY_PROJECT_NAME: ${{ secrets.NETLIFY_PROJECT_NAME }}
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

      - name: Deploy to Netlify
        run: netlify deploy --dir ./output --functions ./netlify/functions --prod --auth ${{ secrets.NETLIFY_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
