name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        working-directory: ./api
        run: bun install

      - name: Install Ghostscript
        run: sudo apt-get update && sudo apt-get install -y ghostscript

      - name: Run Tests
        working-directory: ./api
        run: bun test
